# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-native (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-native (iOS)
  pod 'SwiftyJSON', '~> 4.0'

end

target 'ios-native (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-native (macOS)

end
